### ISSUE TITLE
Small typo in "Explore Integrations" page

### ISSUE THREAD

**Issue by sibylmarziopulcini** [Budibase/website#115]
In the "Oracle" tile the abstract says.. "Use PostgreSQL ..." It should be "Use Oracle as..." probably a wrong cut&paste.
Regards,
Marzio

**Comment by priyanshu2k3** [comment]
hey can i work on this

**Comment by priyanshu2k3** [comment]
hey i have rectified the typo pls check

**Comment by sibylmarziopulcini** [comment]
Maybe just a cache issue on my phone but Oracle seems disappeared in https://budibase.com/integrations/
Can you please check?
