### ISSUE TITLE
Responsive Components box on Forms page is not responsive

### ISSUE THREAD

**Issue by daviewales** [Budibase/website#61]
This is a little ironic!

On the [Forms](https://budibase.com/forms) page, at a very specific screen width: 1440px, the 'Responsive Components' box title text overlaps the description text:
<img width="280" alt="Screen Shot 2022-02-07 at 9 46 21 pm" src="https://user-images.githubusercontent.com/2499066/152774075-66550532-c7f8-4eb4-85c5-6e1c44a0f403.png">

I'm using Firefox 96.0.3 on macOS 10.13.6.

**Comment by joebudi** [comment]
Hi. A fix for this will go out in the next 24 hours.

**Comment by daviewales** [comment]
It looks like that fixed it! Thanks!
